language: generic
sudo: required
cache:
  bundler: true
  directories:
    - boost_1_61_0
    - dependencies
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - p7zip
            - cmake
            - cmake-data
            - libasound2-dev
            - alsa-base
            - alsa-utils
install:
  - cd ./boost_1_61_0
  - sudo ./bootstrap.sh --with-libraries=date_time,filesystem,system
  - sudo ./b2 install
  - cd ..
script:
  - mkdir ./bin/ && cd ./bin/
  - cmake .. -DEXTRA_INCDIR=./dependencies/include
  - make
