language: general

sudo: required

cache:
  directories:
    - boost_1_61_0/stage
    - boost_1_61_0/boost
    - boost_1_61_0/cached_mark

dist: xenal

os: linux

env:
  matrix:
    - CXX="g++-6" CC="gcc-6"
    - CXX="clang-3.8" CC="clang-3.8"
      
# Installing scripts
before_install:
    - sh ./build/travis_install_deps.sh
install:
    - mkdir ./bin/ && cd ./bin/
    - cmake .. -DLINK_BOOST=ON -DEXTRA_LIBDIR=../boost_1_61_0/stage/lib/ -DEXTRA_INCDIR=../boost_1_61_0/
script:
    - make
