language: generic
sudo: required
dist: bionic
git:
  depth: 1
  quiet: true
  submodules: true
cache:
  directories:
    - CMakeFiles/
    - vcpkg/
    - dependencies/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
            - p7zip
            - libgl-dev
            - mesa-common-dev
install:
  - ./Scripts/CILinuxVcpkgInstall.sh
script:
  - git submodule update --recursive --init
  - mkdir cmakeBuild && cd cmakeBuild
  - export CXX=g++-9 CC=gcc-9
  - cmake -DCMAKE_TOOLCHAIN_FILE=/home/travis/build/Infinideastudio/NEWorld/dependencies/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . --target Core.CodeGen -- -j8
  - cmake .
  - cmake --build . -- -j8
