language: generic
sudo: required
cache:
  bundler: true
  directories:
    - boost_1_61_0
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX_COMPILER=g++-6.1
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-6.1
            - p7zip
            - cmake
            - cmake-data
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - freeglut3-dev
before_install:
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo apt-get -yq update
  - sudo apt-get install -y libsdl2-dev libsdl2-image-dev
  - wget http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.7z
  - p7zip -d ./boost_1_61_0.7z > 7zlog.txt
  - cd ./boost_1_61_0
  - ./bootstrap.sh --with-libraries=date_time,filesystem,system
  - sudo ./b2 install
  - cd ..
install:
  - mkdir ./bin/ && cd ./bin/
  - cmake .. -DLINK_BOOST=ON
  - make
script:
  - echo None.

