language: generic
sudo: required
dist: bionic
cache:
  directories:
    - CMakeFiles/
    - vcpkg/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
            - p7zip
            - cmake
            - cmake-data
            - libgl-dev
            - mesa-common-dev
install:
  - |
    git clone https://github.com/Microsoft/vcpkg.git
    cd ./vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg integrate install
    ./vcpkg install sdl2 sdl2-image glew rpclib
    cd ..
script:
  - mkdir cmakeBuild && cd cmakeBuild
  - export CXX=g++-8 CC=gcc-8
  - cmake -DCMAKE_TOOLCHAIN_FILE=/home/travis/build/Infinideastudio/NEWorld/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - make -j8
