language: generic
sudo: required
dist: trusty
cache:
  directories:
    - boost_1_61_0/stage
    - boost_1_61_0/boost
    - bin/CMakeFiles/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - p7zip
            - cmake
            - cmake-data
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - libglew-dev
            - libfreetype6-dev
            - libsdl2-dev
            - libsdl2-image-dev
install:
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++ -f
  - sudo ln -s /usr/include/freetype2/freetype /usr/include/freetype -f

  - wget http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.7z
  - rm -rf ./boost_1_61_0/
  - p7zip -d ./boost_1_61_0.7z
  - cd ./boost_1_61_0
  - touch cached_mark
  - ./bootstrap.sh --with-libraries=date_time,filesystem,system
  - ./b2
  - cd ..
  
  #- pwd
  #- ls /home/travis/build/Infinideastudio/NEWorld/boost_1_61_0/boost
  #- ls /home/travis/build/Infinideastudio/NEWorld/boost_1_61_0/stage/lib
  #- sudo ln -s /home/travis/build/Infinideastudio/NEWorld/boost_1_61_0/boost /usr/include
  #- ls /usr/include
  #- sudo ln -s /usr/
  #- ls /usr/include/freetype2
  #- ls /usr/include/freetype2/freetype
script:
  - cd ./bin/
  - ls ../boost_1_61_0/
  - ls ../boost_1_61_0/boost/
  - cmake .. -DLINK_BOOST=ON -DEXTRA_LIBDIR=./boost_1_61_0/stage/lib/ -DEXTRA_INCDIR=./boost_1_61_0/ -Wno-dev
  #- cat ./Makefile
  - make VERBOSE=1
  - cd ..
