version: '{build}'
branches:
  only:
  - renew
clone_folder: C:\NEWorld
before_build:
- ps: >-
    7zip
    7z
    (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/Infinideastudio/NEWorld-binaries/master/dependencies.exe','C:\NEWorld\dependencies.exe')
    C:\NEWorld\dependencies.exe > C:\NEWorld\temp.txt
    #(new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/Infinideastudio/NEWorld-binaries/master/dependencies.exe','C:\NEWorld\dependencies.exe')
build:
  project: build/VisualStudio_v14/NEWorld.sln
  verbosity: minimal
