version: '{build}'
branches:
  only:
  - renew
  - ci
cache:
  - boost
  - dependencies
clone_folder: C:\NEWorld
clone_depth: 1
install:
# Install Boost libraries
  - if not exist "boost\" mkdir boost
  - cd boost\
  - appveyor-retry nuget install boost_system-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_filesystem-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_date_time-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_regex-vc140 -Version 1.61.0 > nul
  - cd ..
# Install other dependencies
  - appveyor DownloadFile https://raw.githubusercontent.com/Infinideastudio/NEWorld-binaries/master/dependencies.exe
  - C:\NEWorld\dependencies.exe > nul
# Link
  - mklink /D dependencies\include\boost C:\NEWorld\boost\boost.1.61.0.0\lib\native\include\boost
  - mkdir dependencies\lib\boostlib
  - mklink dependencies\lib\boostlib\libboost_filesystem-vc140-mt-gd-1_61.lib C:\NEWorld\boost\boost_filesystem-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_filesystem-vc140-mt-gd-1_61.lib
  - mklink dependencies\lib\boostlib\libboost_system-vc140-mt-gd-1_61.lib C:\NEWorld\boost\boost_system-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_system-vc140-mt-gd-1_61.lib
  - mklink dependencies\lib\boostlib\libboost_date_time-vc140-mt-gd-1_61.lib C:\NEWorld\boost\boost_date_time-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_date_time-vc140-mt-gd-1_61.lib
  - mklink dependencies\lib\boostlib\libboost_regex-vc140-mt-gd-1_61.lib C:\NEWorld\boost\boost_regex-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_regex-vc140-mt-gd-1_61.lib
build:
  project: build/VisualStudio_v14/NEWorld.sln
  verbosity: minimal
on_success:
  # Create an archive
  - 7z a "c:\NEWorld.zip" .\
  - appveyor PushArtifact c:\NEWorld.zip
