version: '{build}'
cache:
  - boost\boost.1.61.0.0\lib\native\include\boost
  - dependencies
platform:
  - x86
  - Any CPU
configuration:
  - Debug
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  # Install dependencies
  - rd/s/q boost\
  - rd/s/q dependencies\
  - if not exist "boost\" .\build\appveyor_install.bat
build:
  project: build/VisualStudio_v14/NEWorld.sln
  verbosity: minimal
on_success:
  # Create an archive
  - 7z a "c:\NEWorld_Core.zip" .\res .\licenses > nul
  - cd .\build\visualstudio_v14\bin\Win32\Debug
  - 7z a "c:\NEWorld_Core.zip" *.exe *.dll .\Plugins\*.dll > nul
  - appveyor PushArtifact c:\NEWorld_Core.zip
