image: Visual Studio 2017
version: '{build}'
cache: c:\tools\vcpkg\installed\
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  - if %PLATFORM% equ Win32 (vcpkg.exe install sdl2 sdl2-image glew rpclib) else (vcpkg.exe install sdl2:x64-windows sdl2-image:x64-windows glew:x64-windows rpclib:x64-windows) > nul
before_build:
  - mkdir projectBuild
  - cd projectBuild
  - if %CONFIGURATION% equ Debug (if %PLATFORM% equ Win32 (cmake ../ -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" ))
  - if %CONFIGURATION% equ Release (if %PLATFORM% equ Win32 (cmake ../ -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" ))
  - if %CONFIGURATION% equ Debug (if %PLATFORM% equ x64 (cmake ../ -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" ))
  - if %CONFIGURATION% equ Release (if %PLATFORM% equ x64 (cmake ../ -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" ))
  - cd ..
build:
  project: projectBuild/NEWorld.sln
  verbosity: minimal
on_success:
  # Create an archive
  - 7z a c:\NEWorld.zip .\Docs
  - cd .\projectBuild
  - 7z a c:\NEWorld.zip .\Product-%CONFIGURATION%
  - 7z a c:\NEWorld.zip .\SDK
  - if %PLATFORM% equ x64 rename c:\NEWorld.zip NEWorld_x64.zip
  - if %PLATFORM% equ x64 (appveyor PushArtifact c:\NEWorld_x64.zip) else (appveyor PushArtifact c:\NEWorld.zip)
  