image: Visual Studio 2019
version: '{build}'
cache: c:\tools\vcpkg\installed\
platform:
  - x64
configuration:
  - Debug
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - .\vcpkg.exe integrate install
  - (vcpkg.exe install sdl2:x64-windows sdl2-image:x64-windows glew:x64-windows rpclib:x64-windows sqlite3:x64-windows wangle:x64-windows) > nul
  - cd %APPVEYOR_BUILD_FOLDER%
before_build:
  - git submodule update --recursive --init
  - mkdir projectBuild
  - cd projectBuild
  - cmake ../ -G "Visual Studio 16 2019" -A %PLATFORM% -DVCPKG_USED=TRUE -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_TOOLCHAIN_FILE="C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
  - cd ..
build:
  project: projectBuild/NEWorld.sln
  verbosity: minimal
on_success:
  # Create an archive
  - 7z a c:\NEWorld.zip .\Docs
  - cd .\projectBuild
  - 7z a c:\NEWorld.zip .\Product
  - 7z a c:\NEWorld.zip .\SDK
  - appveyor PushArtifact c:\NEWorld.zip
  