version: '{build}'
branches:
  only:
  - renew
  - ci
cache:
  - boost
  - dependencies
clone_folder: C:\NEWorld
clone_depth: 1
before_build:
# Install Boost libraries
  - mkdir boost
  - cd boost\
  - appveyor-retry nuget install boost_atomic-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_system-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_filesystem-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_chrono-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_date_time-vc140 -Version 1.61.0 > nul
  - appveyor-retry nuget install boost_thread-vc140 -Version 1.61.0 > nul
  - dir
  - cd ..
# Install other dependencies
  - ps: (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/Infinideastudio/NEWorld-binaries/master/dependencies.exe','C:\NEWorld\dependencies.exe')
  - C:\NEWorld\dependencies.exe > nul
# Link
  - cd dependencies\include
  - mklink \D boost "C:\NEWorld\boost\boost.1.61.0.0\lib\native\include"
build:
  project: build/VisualStudio_v14/NEWorld.sln
  verbosity: minimal
