image: Visual Studio 2017
version: '{build}'
cache: c:\tools\vcpkg\installed\
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  - if %PLATFORM% equ x86 (vcpkg.exe install sdl2 sdl2-image glew rpclib freetype) else (vcpkg.exe install sdl2:x64-windows sdl2-image:x64-windows glew:x64-windows rpclib:x64-windows freetype:x64-windows) > nul
build:
  project: Build/VisualStudio_v15/NEWorld.sln
  verbosity: minimal
on_success:
  # Create an archive
  - 7z a c:\NEWorld.zip .\licenses > nul
  - cd .\release
  - 7z a c:\NEWorld.zip . > nul
  - if %PLATFORM% equ x64 rename c:\NEWorld.zip NEWorld_x64.zip
  - if %PLATFORM% equ x64 (appveyor PushArtifact c:\NEWorld_x64.zip) else (appveyor PushArtifact c:\NEWorld.zip)
  