version: '{build}'

clone_folder: C:\NEWorld
clone_depth: 1
install:
# Install Boost libraries
  - if not exist "boost\" mkdir init_flag
  - if exist "C:\NEWorld\init_flag\" mkdir boost
  - if exist "C:\NEWorld\init_flag\" cd boost\
  - if exist "C:\NEWorld\init_flag\" appveyor-retry nuget install boost_system-vc140 -Version 1.61.0 > nul
  - if exist "C:\NEWorld\init_flag\" appveyor-retry nuget install boost_filesystem-vc140 -Version 1.61.0 > nul
  - if exist "C:\NEWorld\init_flag\" appveyor-retry nuget install boost_date_time-vc140 -Version 1.61.0 > nul
  - if exist "C:\NEWorld\init_flag\" appveyor-retry nuget install boost_regex-vc140 -Version 1.61.0 > nul
  - if exist "C:\NEWorld\init_flag\" cd ..
# Install other dependencies
  - if exist "C:\NEWorld\init_flag\" appveyor DownloadFile https://raw.githubusercontent.com/Infinideastudio/NEWorld-binaries/master/dependencies.exe
  - if exist "C:\NEWorld\init_flag\" C:\NEWorld\dependencies.exe > nul
# Link
  - if exist "C:\NEWorld\init_flag\" mklink /D dependencies\include\boost C:\NEWorld\boost\boost.1.61.0.0\lib\native\include\boost
  - if exist "C:\NEWorld\init_flag\" mkdir dependencies\lib\boostlib
  - if exist "C:\NEWorld\init_flag\" copy C:\NEWorld\boost\boost_filesystem-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_filesystem-vc140-mt-gd-1_61.lib dependencies\lib\boostlib
  - if exist "C:\NEWorld\init_flag\" copy C:\NEWorld\boost\boost_system-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_system-vc140-mt-gd-1_61.lib dependencies\lib\boostlib
  - if exist "C:\NEWorld\init_flag\" copy C:\NEWorld\boost\boost_date_time-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_date_time-vc140-mt-gd-1_61.lib dependencies\lib\boostlib
  - if exist "C:\NEWorld\init_flag\" copy C:\NEWorld\boost\boost_regex-vc140.1.61.0.0\lib\native\address-model-32\lib\libboost_regex-vc140-mt-gd-1_61.lib dependencies\lib\boostlib
build:
  project: build/VisualStudio_v14/NEWorld.sln
  verbosity: minimal
on_success:
# Create an archive
  - 7z a "c:\NEWorld.zip" .\bin\*.exe .\bin\*.dll .\plugins\*.dll .\res .\licenses
  - appveyor PushArtifact c:\NEWorld.zip
