image: Visual Studio 2019
version: '{build}'
cache:
  - C:\neworld-dependency.zip
platform:
  - x64
configuration:
  - Debug
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  - ps: |
      cd C:\
      $fileToCheck = "C:\neworld-dependency.zip"
      if (!(Test-Path $fileToCheck -PathType leaf))
      {
          echo "Dependency file not cached, downloading dependency"
          curl -O neworld-dependency.zip https://distribute.newinfinideas.org/neworld-dependency.zip
      }
      7z x neworld-dependency.zip
  - cd %APPVEYOR_BUILD_FOLDER%
before_build:
  - git submodule update --recursive --init
  - mkdir projectBuild
  - cd projectBuild
  - cmake ../ -G "Visual Studio 16 2019" -A %PLATFORM% -DVCPKG_USED=TRUE -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_TOOLCHAIN_FILE="C:/neworld/scripts/buildsystems/vcpkg.cmake"
  - cmake --build . --target Core.CodeGen
  - cmake .
  - cd ..
build:
  project: projectBuild/NEWorld.sln
  verbosity: minimal
on_success:
  # Create an archive
  - 7z a c:\NEWorld.zip .\Docs
  - cd .\projectBuild
  - 7z a c:\NEWorld.zip .\Product
  - 7z a c:\NEWorld.zip .\SDK
  - appveyor PushArtifact c:\NEWorld.zip
  